apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-app-prod
  namespace: openshift-gitops
spec:
  project: default
  sources:
    - chart: coffee-app
      repoURL: 663151261323.dkr.ecr.eu-central-1.amazonaws.com
      targetRevision: 2023-12-08-14-18-c2c7e45b6d245f5b9bf2ebaed475f33575826095
      helm:
        releaseName: coffee-app-prod
        valueFiles:
          - $values/prod/values.yaml
    - directory:
      path: prod/resources
      repoURL: git@github.com:andifg/coffee-app-gitops.git
    - repoURL: git@github.com:andifg/coffee-app-gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: coffee-app
