apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-pipeline-test
  namespace: openshift-gitops
spec:
  project: default
  source:
    chart: coffee-app
    repoURL: 663151261323.dkr.ecr.eu-central-1.amazonaws.com/coffee-app-chart-repo
    targetRevision: 2023-07-22-17-05-2120881f0025cee65eadd820ca787bf6921d9b41
    helm:
      releaseName: coffee-app
  destination:
    server: "https://kubernetes.default.svc"
    namespace: coffee-app
