apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-app-prod
  namespace: openshift-gitops
spec:
  project: default
  source:
    chart: coffee-app
    repoURL: 663151261323.dkr.ecr.eu-central-1.amazonaws.com
    targetRevision: 2023-08-15-11-09-80daa67fdddb93bb66dcfb3a045ea992c7bfa581
    helm:
      releaseName: coffee-app-prod
  destination:
    server: "https://kubernetes.default.svc"
    namespace: coffee-app
