apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-app-prod
  namespace: openshift-gitops
spec:
  project: default
  source:
    chart: coffee-app
    repoURL: 663151261323.dkr.ecr.eu-central-1.amazonaws.com
    targetRevision: 2023-08-13-16-03-60c5442014a8f946548adc513bbb0ebe95f4bc55
    helm:
      releaseName: coffee-app-prod
  destination:
    server: "https://kubernetes.default.svc"
    namespace: coffee-app
