apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-app-prod
  namespace: openshift-gitops
spec:
  project: default
  source:
    chart: coffee-app
    repoURL: 663151261323.dkr.ecr.eu-central-1.amazonaws.com
    targetRevision: 2023-08-06-17-08-fcbed8b7d299bf961013593a5ac0f53cba566896
    helm:
      releaseName: coffee-app-prod
  destination:
    server: "https://kubernetes.default.svc"
    namespace: coffee-app
