apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-app-prod
  namespace: openshift-gitops
spec:
  project: default
  sources:
    - chart: coffee-app
      repoURL: 663151261323.dkr.ecr.eu-central-1.amazonaws.com
      targetRevision: 2023-08-15-11-31-dc27f0f740112b83a3734a2e80ac900611939867
      helm:
        releaseName: coffee-app-prod
    - directory:
      path: prod/resources
      repoURL: git@github.com:andifg/coffee-app-gitops.git
  destination:
    server: "https://kubernetes.default.svc"
    namespace: coffee-app
