apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-app-prod
  namespace: openshift-gitops
spec:
  project: default
  sources:
    - chart: coffee-app
      repoURL: 663151261323.dkr.ecr.eu-central-1.amazonaws.com
      targetRevision: 2024-04-13-17-37-3f3e0667e27713a8eceb17e46c7ced7c97af48b8
      helm:
        releaseName: coffee-app-prod
        valueFiles:
          - $values/prod/values.yaml
    - directory:
      path: prod/resources
      repoURL: git@github.com:andifg/coffee-app-gitops.git
    - repoURL: git@github.com:andifg/coffee-app-gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: coffee-app
