fullnameOverride: ""
backend:
  log_level: "info"
  image:
    name: image-registry.openshift-image-registry.svc:5000/coffee-app-build/backend:2024-06-16-14-39-b2892ef0dfb154843062931aa414e793cc74a7aa
  ingress:
    host: api.beanscore.de
frontend:
  image:
    name: image-registry.openshift-image-registry.svc:5000/coffee-app-build/frontend:2024-06-19-19-46-0067b6859df7bfe2bcbe18836e214031a59960cd
  ingress:
    host: beanscore.de
resizer:
  logLevel: "info"
  image:
    name: image-registry.openshift-image-registry.svc:5000/coffee-app-build/resizer:2024-05-06-20-15-fa8e3ac065c0450ca1aa92e9f5716545a11a6539
mongodb:
  auth:
    existingSecret: mongodb-root-password
minio:
  auth:
    existingSecret: minio-credentials
keycloak:
  ingress:
    hostname: auth.beanscore.de
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    extraTls:
      - hosts:
          # Make sure its same as ingress.hostname
          - auth.beanscore.de
        secretName: coffee-app-keycloak-tls
  postgresql:
    auth:
      existingSecret: keycloak-postgres-password
  auth:
    adminUser: admin
    existingSecret: keycloak-admin-password
backup:
  enabled: true
  keycloak:
    enabled: true
  minio:
    enabled: true
  mongodb:
    enabled: true
