fullnameOverride: ""
backend:
  log_level: "info"
  image:
    name: image-registry.openshift-image-registry.svc:5000/coffee-app-build/backend:2024-10-07-19-34-c78b416afcdbc8923a1c6d1b315f3e51e5b2e51f
  ingress:
    host: api.beanscore.de
frontend:
  image:
    name: image-registry.openshift-image-registry.svc:5000/coffee-app-build/frontend:2024-10-03-08-15-e650e76f15d91dfef02c563fc73961fbadc12f7a
  ingress:
    host: beanscore.de
resizer:
  logLevel: "info"
  image:
    name: image-registry.openshift-image-registry.svc:5000/coffee-app-build/resizer:2024-06-29-06-42-052f5a55769ae31beab484672762a676df7b8504
mongodb:
  auth:
    existingSecret: mongodb-root-password
minio:
  auth:
    existingSecret: minio-credentials
keycloak:
  ingress:
    hostname: auth.beanscore.de
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    extraTls:
      - hosts:
          # Make sure its same as ingress.hostname
          - auth.beanscore.de
        secretName: coffee-app-keycloak-tls
  postgresql:
    auth:
      existingSecret: keycloak-postgres-password
  auth:
    adminUser: admin
    existingSecret: keycloak-admin-password
backup:
  enabled: true
  keycloak:
    enabled: true
  minio:
    enabled: true
  mongodb:
    enabled: true
