fullnameOverride: ""
backend:
  log_level: "info"
  image:
    name: image-registry.openshift-image-registry.svc:5000/coffee-app-build/backend:2024-10-21-19-47-c9257212e421c390e58ae287a3c92abc59301fc6
  ingress:
    host: api.beanscore.de
frontend:
  image:
    name: image-registry.openshift-image-registry.svc:5000/coffee-app-build/frontend:2024-10-13-12-09-504616a4a08c8d118522411abb235adc83e24923
  ingress:
    host: beanscore.de
resizer:
  logLevel: "info"
  image:
    name: image-registry.openshift-image-registry.svc:5000/coffee-app-build/resizer:2024-10-13-13-36-63f4e96cccaaba4d0384a760876640812689f925
mongodb:
  auth:
    existingSecret: mongodb-root-password
minio:
  auth:
    existingSecret: minio-credentials
keycloak:
  ingress:
    hostname: auth.beanscore.de
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    extraTls:
      - hosts:
          # Make sure its same as ingress.hostname
          - auth.beanscore.de
        secretName: coffee-app-keycloak-tls
  postgresql:
    auth:
      existingSecret: keycloak-postgres-password
  auth:
    adminUser: admin
    existingSecret: keycloak-admin-password
backup:
  enabled: true
  keycloak:
    enabled: true
  minio:
    enabled: true
  mongodb:
    enabled: true
