# Default values for coffee-app.
nameOverride: ""
fullnameOverride: ""
backend:
  containerPort: 8000
  replicaCount: 1
  image:
    name: image-registry.openshift-image-registry.svc:5000/coffee-app-build/backend:2024-06-14-06-02-daeef63975d6690071704c2cb3aa2488f4a9cd4a
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    host: api.coffee-app.apps.ocp4.gummy-bears.de
    path: /
    pathType: ImplementationSpecific
    tls:
      enabled: true
      certManager:
        enabled: true
      # If certManger is eanaled, this secret will be created, otherwise it needs to exist already
      secretName: api-coffee-app-tls
  mongodb:
    host: mongodb
    port: 27017
    username: root
    # This secret needs to exist already
    passwordSecretName: mongodb-root-password
frontend:
  containerPort: 8080
  replicaCount: 1
  image:
    name: image-registry.openshift-image-registry.svc:5000/coffee-app-build/frontend:2024-05-23-16-47-d2a38458f592f0588bad889a2b369f37cd533e19
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    host: coffee-app.apps.ocp4.gummy-bears.de
    path: /
    pathType: ImplementationSpecific
    tls:
      enabled: true
      certManager:
        enabled: true
      secretName: coffee-app-tls
imagePullSecrets: []
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
autoscaling: {}
resizer:
  image:
    name: image-registry.openshift-image-registry.svc:5000/coffee-app-build/resizer:2024-05-06-20-15-fa8e3ac065c0450ca1aa92e9f5716545a11a6539
